version: '3.4'

services:
  cli:
    image: manga-downloader-cli
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./data:/app/out
    stdin_open: true
    tty: true

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=debug
    ports:
      - 8191:8191
    restart: unless-stopped
